# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spelling.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spelling.proto',
  package='unary',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0espelling.proto\x12\x05unary\"\x1f\n\x0fSpellingBeeWord\x12\x0c\n\x04word\x18\x01 \x01(\t\"9\n\x17SpellingBeeWordResponse\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t2\\\n\x0bSpellingBee\x12M\n\x11GetServerResponse\x12\x16.unary.SpellingBeeWord\x1a\x1e.unary.SpellingBeeWordResponse\"\x00\x62\x06proto3'
)




_SPELLINGBEEWORD = _descriptor.Descriptor(
  name='SpellingBeeWord',
  full_name='unary.SpellingBeeWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='unary.SpellingBeeWord.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=56,
)


_SPELLINGBEEWORDRESPONSE = _descriptor.Descriptor(
  name='SpellingBeeWordResponse',
  full_name='unary.SpellingBeeWordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='unary.SpellingBeeWordResponse.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='unary.SpellingBeeWordResponse.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['SpellingBeeWord'] = _SPELLINGBEEWORD
DESCRIPTOR.message_types_by_name['SpellingBeeWordResponse'] = _SPELLINGBEEWORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpellingBeeWord = _reflection.GeneratedProtocolMessageType('SpellingBeeWord', (_message.Message,), {
  'DESCRIPTOR' : _SPELLINGBEEWORD,
  '__module__' : 'spelling_pb2'
  # @@protoc_insertion_point(class_scope:unary.SpellingBeeWord)
  })
_sym_db.RegisterMessage(SpellingBeeWord)

SpellingBeeWordResponse = _reflection.GeneratedProtocolMessageType('SpellingBeeWordResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPELLINGBEEWORDRESPONSE,
  '__module__' : 'spelling_pb2'
  # @@protoc_insertion_point(class_scope:unary.SpellingBeeWordResponse)
  })
_sym_db.RegisterMessage(SpellingBeeWordResponse)



_SPELLINGBEE = _descriptor.ServiceDescriptor(
  name='SpellingBee',
  full_name='unary.SpellingBee',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetServerResponse',
    full_name='unary.SpellingBee.GetServerResponse',
    index=0,
    containing_service=None,
    input_type=_SPELLINGBEEWORD,
    output_type=_SPELLINGBEEWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPELLINGBEE)

DESCRIPTOR.services_by_name['SpellingBee'] = _SPELLINGBEE

# @@protoc_insertion_point(module_scope)
